spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver